### ISSUE TITLE
저기요

### ISSUE THREAD

**Issue by Kootaehoon** [norangLemon/naverWeather#1]
코드가 실행이안되는데요

**Comment by rkzktl2gh** [comment]
코드수정하면되요

**Comment by norangLemon** [comment]
이슈를 작성하실 때는 어떻게 했는데 무슨 문제를 일으켰는지 말씀해주십시오.
이렇게 단순히 '되지 않는다'이면 이 코드가 의도한 동작인지 버그인지 알 수 없습니다.

또한 이 코드는 작성한 지 3년 가량 된 코드로, 실행환경 및 라이브러리에 따라서 더이상 작동하지 않을 수 있습니다.
