### ISSUE TITLE
@KOOTAEHOON님에게

### ISSUE THREAD

**Issue by rkzktl2gh** [norangLemon/naverWeather#2]
초기화면에서 1번과 2번이 아닌 다른 것을 입력하면 오류가 나던데 어떻게 하나요

**Comment by Kootaehoon** [comment]
기존의 int형으로 입력받는 input()함수를 int형이 아닌 문자형으로 입력받도록 하고,
 if문에서 입력받는 1과 2를 숫자가 아닌 문자로 받기위해 작은 따옴표로 묶어주시고
1과 2가 아닌 다른 문자는 elif문을 통해 처리해주시면 될것같습니다.

**Comment by norangLemon** [comment]
이 저장소의 코드에 관련된 내용이 아닌 것 같아 닫습니다.
